# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: postgres
  password: 18012001
  host: 127.0.0.1
  # port: 5433
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: restaurant_zens

test:
  <<: *default
  database: restaurant_zens
#
production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
